name: Test

on:
    push:
        branches:
            - "master"
    pull_request:
        types: [ready_for_review, synchronize, opened]
    schedule:
        - cron: '0 1 * * *'

jobs:
    unit:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [12.x]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install
              run: yarn
            - name: Test
              run: yarn test:unit

    
    e2e:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [12.x]

        steps:
            - uses: actions/checkout@v2
              with:
                  repository: ArkEcosystem/core
                  ref: master
            - uses: actions/checkout@v2
              with:
                  path: plugins/dapp-custom-transaction-example
            - name: Find and Replace
              uses: jacobtomlinson/gha-find-replace@master
              with:
                  find: "\"@arkecosystem/core-snapshots\": {},"
                  replace: "\"@arkecosystem/core-snapshots\": {}, \"@arkecosystem/custom-transactions\": {},"
                  include: "__tests__/e2e/lib/config/nodes/.*/plugins.js"
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install and build packages
              run: yarn setup && cd __tests__/e2e && ../../node_modules/.bin/tsc && yarn cache clean && yarn install --frozen-lockfile
            - name: Docker compose up
              run: cd __tests__/e2e/lib/config && docker-compose up -d
            - name: Wait 180 sec for docker containers to be up and nodes be running and forged a few blocks
              run: sleep 180
            - name: Run tests
              run: 'cd plugins/dapp-custom-transaction-example && yarn test:e2e'
            - name:
              if: failure() && github.event_name == 'schedule'
              uses: JasonEtco/create-an-issue@master
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  filename: plugins/dapp-custom-transaction-example/.github/ISSUE_TEMPLATE.md
            - name: Output results - node0
              if: always()
              run: docker logs config_core0_1
            - name: Output results - node1
              if: always()
              run: docker logs config_core1_1
            - name: Output results - node2
              if: always()
              run: docker logs config_core2_1
